### ISSUE TITLE
설치하고 나서도 mecab을 install하라고 뜨네요..

### ISSUE THREAD

**Issue by ChoYoungSeo** [SOMJANG/Mecab-ko-for-Google-Colab#2]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/14102454/74418524-dc336d80-4e8b-11ea-9bfd-783799cab30f.png">

실행 방법 그대로 하였는데도, 왜 Tagger is not defined에 설치하라고 하는지 모르겠습니다.

**Comment by SOMJANG** [comment]
혹시 해당 Colab ipynb파일링크 공유해주실수 있을까요?

**Comment by SOMJANG** [comment]
링크 공유해주시면 최대한 빠르게 확인해서 답변드리겠습니다!

**Comment by ChoYoungSeo** [comment]
오늘 확인을 해보니, 다시 잘 돌아가는 것 같습니다. 순간적인 문제, 혹은 제 실수였던 것 같네요. 감사합니다!

**Comment by SOMJANG** [comment]
다행입니다! 감사합니다!
