### ISSUE TITLE
NameError: name 'Tagger' is not defined

### ISSUE THREAD

**Issue by SOMJANG** [SOMJANG/Mecab-ko-for-Google-Colab#5]
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/konlpy/tag/_mecab.py in __init__(self, dicpath)
     76         try:
---> 77             self.tagger = Tagger('-d %s' % dicpath)
     78             self.tagset = utils.read_json('%s/data/tagset/mecab.json' % utils.installpath)

NameError: name 'Tagger' is not defined

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
1 frames
/usr/local/lib/python3.7/dist-packages/konlpy/tag/_mecab.py in __init__(self, dicpath)
     80             raise Exception('The MeCab dictionary does not exist at "%s". Is the dictionary correctly installed?\nYou can also try entering the dictionary path when initializing the Mecab class: "Mecab(\'/some/dic/path\')"' % dicpath)
     81         except NameError:
---> 82             raise Exception('Install MeCab in order to use it: http://konlpy.org/en/latest/install/')
     83 
     84     def __setstate__(self, state):

Exception: Install MeCab in order to use it: http://konlpy.org/en/latest/install/
```

2022년 1월 9일 이후 위와 같은 에러 발생

**Comment by combacsa** [comment]
안녕하세요, https://github.com/konlpy/konlpy/issues/393 에서 보고 찾아왔습니다.

임시방편으로는 `!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/d9206305195583c08400cb2237c837cc42df2e65/scripts/mecab.sh)` 를 `from konlpy.tag import Mecab` 하는 cell 바로 앞에 삽입하시면 작동은 되게 하실 수 있을 것으로 생각됩니다.

**Comment by combacsa** [comment]
https://github.com/konlpy/konlpy/pull/394 로 해결이 가능할지를 검토해보려고 합니다.

혹시 `curl` 하는 `mecab.sh` 를 아래와 같이 교체했을 때 잘 작동되는지 확인을 부탁드려도 괜찮을까요?

* as-is
  * `bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)`
* to-be (temporarily)
  * `bash <(curl -s https://raw.githubusercontent.com/combacsa/konlpy/master/scripts/mecab.sh)`

**Comment by SOMJANG** [comment]
안녕하세요. @combacsa 님! 
말씀하신 방법대로 변경해서 실행해보니 문제없이 작동되는 것을 확인하였습니다.
https://github.com/konlpy/konlpy/pull/394 해당 부분이 merge 되고 나면 문제없이 동작할 것 같습니다!
감사합니다.

**Comment by SOMJANG** [comment]
- to-be (temporarily)
   - `bash <(curl -s https://raw.githubusercontent.com/combacsa/konlpy/master/scripts/mecab.sh)`

일단 임시 방편으로 알려주신 방법 활용해서 업데이트 해두었습니다!
[install_mecab-ko_on_colab_light_220111.sh](https://github.com/SOMJANG/Mecab-ko-for-Google-Colab/blob/9f273a5632cc774f1b025ee156014a8fa1608680/install_mecab-ko_on_colab_light_220111.sh)

감사합니다!
